name: foodapp
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  lottie: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  test: ^1.19.5

flutter:
  uses-material-design: true

  assets:
    - images/

  
  fonts:
    - family: Baloo2
      fonts:
        - asset: fonts/Baloo2-SemiBold.ttf
        
    - family: Noto
      fonts:
        - asset: fonts/NotoSans-SemiBold.ttf
        - asset: fonts/NotoSans-Medium.ttf
        - asset: fonts/NotoSans-Regular.ttf
        - asset: fonts/NotoSans-Light.ttf
      

